name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AU_SECRET_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H orion.cc.andrews.edu >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_rsa" \
          ./www/ \
          monroel@orion.cc.andrews.edu:/homes/Student/undecided/2025a/monroel/www/
